/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.enterprisebtc.kotlin-library-conventions")
}

dependencies {

    api(libs.okHttp)
    implementation(libs.acinqSecp256k1)
    implementation(libs.kotlinxCoroutines)
    implementation(libs.okIo)
    implementation(libs.secureRandom)
    implementation(libs.moshi)
    implementation(libs.guava)

    implementation(libs.kotlin.logging)

}
